### ISSUE TITLE
RC1.0 Todo

### ISSUE THREAD

**Issue by arthurian** [Harvard-ATG/HarmonyLab#53]
List of TODOs to finish up this phase of development for 1.0 release candidate:

CURRENT from 4/20:
- [x] Artie: fix the menu so that clicking outside the menu closes it
- [x] Artie: fix metronome display (broken from font changes)
- [x] Artie: fix the semicolon shortcut since it doesn’t appear to be working (release & depress the pedal)
    - See PR #57 
- [x] Artie: fix the size of the text font used for analysis so it looks better next to the figured bass
- [x] Artie: fix the issue when the figured bass font doesn’t render properly for some reason (only happens sometimes)
- [x] Artie: reduce the size of the pedals
- [ ] Artie: add a non-banking option under “instrument” to disable chord banking behavior and center the chord on the display
- [x] Artie: add admin interface for instructors to create drills, which consist of a set of exercises number from 1..N. Allow instructor to add items using lilypond notation (use Rowland’s script to translate lilypond to MIDI). Show the list of drills in the main menu.
- [x] Artie: email Rowland an example of what an exercise looks like w/ analysis & highlight settings
    - Emailed Rowland details on 3/27 @ 2:45pm
- [x] Bill: arrange meeting for sometime next week or the week after if necessary
- [x] Rowland: update the iChords with figured bass font
- [x] Rowland: review Osnat’s exercises (see below for links to the exercises)
- [ ] Rowland: write documentation about what the thing can do (we’ll put it on github)
- [x] Rowland: check out the possible TE issue, open Firebug in Firefox or the developer console in Chrome and take a screenshot of the page and any error that might be displayed in the console. 

---

OLD from before 3/25:
- [x] Add simple triad completion exercises for [roman numerals](http://en.wikipedia.org/wiki/Roman_numeral_analysis) I, ii, iii, IV, V, vi, vii&#176;
- [x] Remove the top banner in Canvas, but keep the "info" button.
- [x] Record the total time/duration of exercise (start to completion).
- [x] Push "key signature" in an exercise definition, which is separate from the "key."
- [x] Push all analysis options in an exercise definition.
- [x] Increase the font size for all labels and analysis text above/below staff.
- [x] Add ability for user to play notes B4 and C5 (MIDI 71 and 72) to automatically advance to the next exercise. This is for students who are playing on an external keyboard, so they don't have to click the "next" button. 

- [x] Revamp the menus with Roderick's help. Only key thing that should be available/visible to students while playing is the key/key signature. Everything else can be hidden away in menus.
- [x] Remove background image -- keep dark background but make it look more professional. Maybe make a "canvas only" theme??
- [x] Move the exercise prompt (intro) so that it's displayed under the "Exercise Status" on the sheet music and visible while the student is playing. Remove the review text entirely (unnecessary).
